### ISSUE TITLE
Sydney Opera House .3dm Rhino file

### ISSUE THREAD

**Issue by JoostGevaert-Arup** [pollination/pollination-sample-models#2]
Would it be possible to include the Sydney Opera House Rhino .3dm file as well?

I'd like to try out the tutorial from this Youtube video:
https://www.youtube.com/watch?v=rzdKy5xH330

**Comment by mostaphaRoudsari** [comment]
Hi @JoostGevaert-Arup, I can try to find and upload the model, but it is basically the same as importing the HBJSON file in Rhino.

**Comment by JoostGevaert-Arup** [comment]
Sorry for the late reply.
In my head I had already replied haha.
Anway, I didn't know I could also just import the HBJSON into Rhino. Thanks!
